### ISSUE TITLE
Get status code after switching from old client to new one

### ISSUE THREAD

**Issue by ffMathy** [Azure/autorest.typescript#1088]
After switching from Core HTTP 1 to 2 (or is it 6 now?), I am no longer getting a `._response` property on my responses, where I can access (for instance) HTTP status codes and headers etc.

How am I to do this with the new clients?

Great work on all of this by the way. Autorest rocks.

**Comment by deyaaeldeen** [comment]
@ffMathy thanks for the feedback!

Regarding `_response`, you can access the same information using the `onResponse` option. Please see this example for reference: https://github.com/Azure/autorest.typescript/blob/2a2060ce63f48f7838e32b341e7d9e79e207eba6/test/integration/additionalProperties.spec.ts#L172.

**Comment by ffMathy** [comment]
I must say I believe this is quite a big downgrade unfortunately. I often check the status code.

**Comment by deyaaeldeen** [comment]
@ffMathy I am sorry about this. Let me clarify why we did make this change, it was because `_response` did not play well with some response types (`null`, `void`, arrays, etc). If your API returns a null, there is no way to attach `_response` to it, so what were happening before is to return an empty object instead and then we attach `_response` to it. This is problematic because your API could return null as well as the empty object in two different scenarios and there is no way to distinguish between them. To fix this, we decided to make the raw response accessible through the callback so we no longer need to create empty objects if we get nulls or similar.

That being said, you could still generate using the old behavior using the `--use-core-v2=false` flag if you like but IIRC, we're going to deprecate that old behavior at some point.

Please let me know what do you think.

**Comment by sarangan12** [comment]
No more action items on this issue. Closing this for now.
