### ISSUE TITLE
readme.md client construction for mgmt SDK client is incorrect

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1137]
https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/compute/arm-compute#create-and-authenticate-a-computemanagementclient 

in the generated mgmt SDK readme.md. It suggests
```
const { ComputeManagementClient } = require("@azure/arm-compute");
const { DefaultAzureCredential } = require("@azure/identity");
const client = new ComputeManagementClient("<endpoint>", new DefaultAzureCredential());
```

but the correct way to create a mgmt client is 
```
const { ComputeManagementClient } = require("@azure/arm-compute");
const { DefaultAzureCredential } = require("@azure/identity");
const client = new ComputeManagementClient(new DefaultAzureCredential(), subscriptionId);
```

originally comes from https://github.com/Azure/azure-sdk-for-js/issues/16702

**Comment by sarangan12** [comment]
@qiaozha Thanks for raising this issue. I have looked into this issue and here is my opinion:

1. I agree with your analysis that for the `ComputeManagementClient`, the sample code `const client = new ComputeManagementClient("<endpoint>", new DefaultAzureCredential());` is incorrect. It has to be `const client = new ComputeManagementClient(new DefaultAzureCredential(), subscriptionId);`. 
2. But, is this solution generic? i.e. Can we change the code in `README.md.hbs` file to the `ComputeManagementClient` format and assume it will work for all the SDKs? The answer will be No. (It will work for most scenarios. Not all scenarios). Let us take a look at the constructor [here](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/datacatalog/arm-datacatalog/src/dataCatalogRestClient.ts#L37). The modified code will not work for this case. 
3. What is the correct way to solve? Programmatically, we need to analyze the client class file, its constructor and build this code. But, This code will be unnecessarily complicated and I would not do it. 
4. What is my suggestion? Since the code will be different for different SDKs, this is one of the reasons I do not like code to be embedded in `README.md` files. We could easily point them to samples repository. 
5. Also, remember `README.md` file is part of the metadata and you would probably generate it once at the beginning for new SDKs or during migrations such as this one. But, after this generation, you will never regenerate the metadata.

To summarize, Here are my recommendations:
1. **Option 1**
You could modify the logic in `README.md.hbs` to point 3 mentioned above. It will be complicated and I would not suggest you doing it. I would rather spend your time in more useful issues that could enhance the generator. But, if you are really interested in solving this issue, I would not stop you.
2. **Option 2**
You could leave the code as such and modify the final `README.md` file manually. Because, after initial generation, you are not going to regenerate the metadata. So, it will never be impacted. I am Ok with this option. But, I still feel it is not correct to leave such incorrect code within the generator.
3. **Option 3**
Remove the part which has the code in `README.md.hbs`. Instead of the code, rewrite that portion and point it to the samples repo explaining that the repo will have samples to show how to use credentials. Even the `README.md` files in data plane SDKs can point to the samples repo as you are just explaining how to use credentials. This option will work for all SDKs and simple to implement and will be correct now and in the future. So, this is the option that I would recommend. 

For your next question, Yes. This is a good candidate for Contribution. Please go through my recommendations and let me know your thoughts.

**Comment by qiaozha** [comment]
@sarangan12 Thanks for your detailed suggestion. I will discuss with @nickzhums and @lirenhe about it and get back to you.

**Comment by qiaozha** [comment]
close it as PR merged. Thanks
