### ISSUE TITLE
Add reference to track1 SDK homepage in track2 readme.md

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1183]
Per the discussion here, we should add a link in track2 readme.md that points to track1 sdk homepage for track1 sdk customers.
https://github.com/Azure/azure-sdk-for-js/pull/16719

**Comment by ramya-rao-a** [comment]
@qiaozha Isnt this a temporary solution until the Track 2 packages go GA? If so, I would recommend adding the link manually rather than update the code generator for it.

**Comment by qiaozha** [comment]
I think as long as we have customers who are using track1 sdk. we should have this link here to avoid confusion. Not sure how long it will take for customers to migrate to track2. but it did take us more than two years for them migrate from node SDK to js SDK. I prefer not to add that link each time when generate the package between now and then.

**Comment by qiaozha** [comment]
@ramya-rao-a to clarify the details of this issue. 
1. previously, we get an issue from our customer, that complains about the document about JS SDK is out-of-date. which turns out he get the document from the homepage link, and we have changed the homepage link to main branch and this customer is using track1 sdk. 
2. I asked sigang to update all the packages' homepage in feature/v4 branch to point to feature/v4 branch in this PR https://github.com/Azure/azure-sdk-for-js/pull/16719 and was hoping npmjs could show different homepage link for different versions, it turns out the homepage in npmjs can be only point to one place and it will be refresh each time we release a new package regardless the version is formal or preview, And wes suggest us for those onboarded track2 RPs, change the homepage link to main branch but have some comments to hint our customer about the right homepage for track1 sdk see https://github.com/Azure/azure-sdk-for-js/pull/16719#issuecomment-893592234 
3. So I was thinking as long as there're track1 sdk customers, they just can click that homepage link in npmjs and found out it is out of date in terms of track1 sdk. and the migration of track1 to track2 maybe a very long process. I just think maybe we could add it in the code generator. 

About how to identify the version of track1 and track2 packages, my thought is we probably can leverage the information here? https://azure.github.io/azure-sdk/releases/latest/mgmt/js.html

**Comment by ramya-rao-a** [comment]
If you want Track 1 customers to have information on the Track 1 packages even after Track 2 goes live, then you not only need the link to the right readme, but also the link to the right API reference docs. This is because if they organically search for it, they will land on the docs for Track 2

To resolve the confusion for the customer, we cannot just add the link to the feature/v4 branch. You would need to say something like the below. Here I have taken the example of  `@azure/arm-storage`

> For version 16 of this package, please refer to the [readme for v16](https://github.com/Azure/azure-sdk-for-js/tree/feature/v4/sdk/storage/arm-storage) and [API references documentation for v16](https://docs.microsoft.com/javascript/api/@azure/arm-storage/?view=azure-node-legacy)

We will need to ensure we use the right version number for the right package as well as ensure this line is not present for new services that will only have Track 2.

I would recommend you have a sync with the mgmt plane teams for other languages to see what approach was taken there to guide Track 1 users who may land on Track 2 readmes

**Comment by ramya-rao-a** [comment]
@qiaozha Any updates here?

**Comment by qiaozha** [comment]
As track1 SDKs have already been deprecated, and we no longer release track1 SDKs, I don't think this is a valid request now. @lirenhe @xboxeer how do you think ?

**Comment by xboxeer** [comment]
I agree, we should not add link to track 1 sdk anymore

**Comment by qiaozha** [comment]
okay, close it as no longer valid.
