### ISSUE TITLE
[BluePrint] generate blueprint SDK failed with latest code generator beta release

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1218]
Here's the repro steps:
1. use the latest swagger as input. 
2. run the code generation command `autorest --version=3.1.3 --typescript --modelerfour.lenient-model-deduplication --head-as-boolean=true --license-header=MICROSOFT_MIT_NO_VERSION --generate-test --typescript-sdks-folder=/Users/zhangqiaoqiao/work/code/azure-sdk-for-js ../azure-rest-api-specs/specification/blueprint/resource-manager/readme.md --use=@autorest/typescript@6.0.0-beta.13`

Here's the result I am getting: 
![image](https://user-images.githubusercontent.com/55688292/138636337-121ba9ec-2f4b-4ec0-8574-87b5f168688f.png)

**Comment by sarangan12** [comment]
@qiaozha This error can be fixed in two ways:

1. If you search for the `docs: ` in the `src` section, you will find roughly 40 places. Basically, we need to put the comments through a method such as `sanitizeComments` method. In the new `sanitizeComments` method, we just need to replace `*/` with `*\/`. Then this issue will be resolved.
2. Alternatively, you can do a swagger override for this service where you replace the `*/` (in the comments) with `*\/`. This will also resolve the issue. 

Please choose one of the methods and open a PR. I will review and merge the changes. Thanks

**Comment by ramya-rao-a** [comment]
@qiaozha Any updates on which approach you would like to go with here?

**Comment by sarangan12** [comment]
I believe there is no pending action items on this issue. Closing it for now.
