### ISSUE TITLE
generate a minimal version of README.md for RLC

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1269]
Currently, we don't auto generate a README.md for JS RLC, but for the ten mins shippable package purpose, we will need to support that. I wonder what kind of content should we include here ?
Here's an example of manually written README.md https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/purview/purview-catalog-rest/README.md 
But some of the parts are not able to be auto generated. such as the description part and the resource dependencies part. @mikekistler Could you share some of you thoughts with us? Thanks

cc @joheredi @lirenhe

**Comment by mikekistler** [comment]
If the "description part" refers to the description of the service at the top of the README.md, this could be generated if the text there is put into the `info.description` item in the API definition. I know that is not currently common practice for Azure API definitions but I don't think we will get resistance to changing that.

The resource dependencies are harder.  Is it common that services must document dependencies like this or is Purview a special case?

**Comment by joheredi** [comment]
@mikekistler, it is common for human-written sdks. However, for RLC/LLC it would be very hard to get as it is not part of the API definition. I guess a single link to Service Docs would be enough, as they would walk users through creating the resource

I agree that we should just take `info.description` for the description section. It would be great if the API definition included a link to the REST API Doc site and also to the Service Documentation.

Ideally I think a useful minimal readme would contain the following

* Description: We can get this from `info.description`
* General information on how Rest Clients work - This would be the same for every package ([link](https://github.com/Azure/azure-sdk-for-js/blob/main/documentation/rest-clients.md))
* A link to the REST API doc site
* A link to the Service Documentation
* Troubleshooting: This is the same for every package

We don't need to generate samples because the General Rest Clients doc already has some samples on how to instantiate, authenticate and make a call. So those should be enough.

**Comment by mikekistler** [comment]
This looks good to me.

If there is specific information we need like the URL to the REST API Docs or Service Documentation, we could create spec extensions for these, or ask that they be specified in the README.

I'm struggling to recover the context for the dependencies issue.  I don't see any mention of resource dependencies in the hand-written readme.  And I also don't know why a _generated_ library would have dependencies that are not well understood by the generator and thus could be included in the README.  But we can handle that as follow-on work.

**Comment by qiaozha** [comment]
@mikekistler here's the dependencies in the purview catelog readme.md 
![image](https://user-images.githubusercontent.com/55688292/148162686-cc6799b8-973d-4ff3-bf0e-66bd1d093532.png)
which is unknown to the code generator.

**Comment by mikekistler** [comment]
Ah, very good.  I think our recommendation should be that this information be included in `info.description`. I think that's reasonable since it applies to the REST API generally.

Note that `info.description` can contain markdown -- we should make sure we don't damage any markdown formatting in the generation process.

**Comment by qiaozha** [comment]
Does that mean the code generator should put whatever the services team put in the info.description into the readme.md ? and if they don't have such resource dependencies infomation in info.description, then we should not do extra things on it ?

**Comment by joheredi** [comment]
Yeah that's my understanding and it also aligns with the mission and scope of RLCs which is to generate SDKs with minimal human intervention. If a swagger doesn't include enough information for the README we should not try to add it, we should ask service teams to include it in the Swagger
