### ISSUE TITLE
[RLC] Use title as client type

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1272]
I think we should change the client type to the value of `title`, instead of `{value_of_title} + RestClient`. The reasons of doing this change are:

- It is different from other language as they use `{value_of_title}` as client type directly. We should keep consistent with them.
- The value of  `title` is the name of a function which creates client. Most times, the value of `title` is in pascal, which doesn't meet the specification of Typescript code style. For example, [PurviewScanning](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/purview/purview-scanning-rest/src/purviewScanning.ts#L473).

Suggested Changes:
- Change the client type to the value of `title`.
- Change the name function, which creates client, to `create + {value_of_title}`.

**Comment by joheredi** [comment]
Thanks for sharing your thoughts @dw511214992. In general, I like to use Pascal casing for these client factory functions as it looks cleaner for example

```typescript
const client = PurviewScanning();

//vs

const client = createPurviewScanning();
```

It seems to be common in the JavaScript community to Pascal case these functions, and also would feel more familiar for users familiar with classes, just without the `new`.

Though, this wouldn't impact end-users because they are the default exports, so they can choose how they want to import.

```typescript
import NameOfYourLiking from "@azure-rest/purview-scanning"
```

The way we write documentation and samples would likely inspire our customers.

@bterlson my suggestion is that we keep them as we have today and keep documenting them this way, what do you think?

```typescript
import PurviewScanning from "@azure-rest/purview-scanning"
```

**Comment by dw511214992** [comment]
If we still use the `title` as the client factory name, I think it's better to trim `Client` because it's very strange if the `title` ends with `Client`.
For example, if the value of `title` is `FooClient`, then the client name will be `FooClientRestClient` and the client factory name will be `FooClient`. What do you think about it? @joheredi

**Comment by joheredi** [comment]
@qiaozha do you remember if we added the `Client` suffix recently? I think it should be fine to not suffix with `Client`. @qiaozha do you know if there would be any issues around multi client if we do this?

**Comment by qiaozha** [comment]
> @qiaozha do you remember if we added the `Client` suffix recently? I think it should be fine to not suffix with `Client`. @qiaozha do you know if there would be any issues around multi client if we do this?

I don't remember we added this suffix, I think it's fine to remove it if we did.

**Comment by joheredi** [comment]
@dw511214992, @qiaozha, we should be fine removing the Client suffix. Feel free to file a PR with the change and I'll be happy to review

**Comment by lirenhe** [comment]
Close as code merged.
