### ISSUE TITLE
[LLC] Multi type for date format string

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1284]
When swagger definition is:
```
        "startDateTime": {
          "type": "string",
          "description": "The deployment start datetime.",
          "format": "date-time"
        },
```
The generated code is:
```
startDateTime: Date | string;
```
From @xirzec it's weird to not just pick one, either we're deserializing it or not, since it can't be coming over the wire as a Date object.

**Comment by joheredi** [comment]
We are generating this union for Input types only, Output is always a `string` because we cannot safely deserialize without runtime mapping.

The reason these inputs are `string` or `Date` is to give the user a chance to work with them as it is more convenient for their use case. 

For example, if they are round-tripping data from and to the service it may be more convenient to just take the date as received from the service and put it in the request without having to convert it to a `Date`. On the other hand, if users are crafting a request from scratch, it may be more convenient to say `Date.now()` than crafting the date as a string.

I believe this has value, especially since it is for input types, users shouldn't need flow control to work with these types.

@xirzec, @bterlson what do you think?

**Comment by xirzec** [comment]
Yeah for inputs this is fine! I didn't pick up on the fact it was only used that way.

**Comment by joheredi** [comment]
Thanks for the input folks! Closing this issue as I think we have agreement that input types are fine with the union
