### ISSUE TITLE
Client name set by x-ms-code-generation-settings

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1316]
They are still a lot of RPs who set their client name through x-ms-code-generation-settings.name in their swaggers, and our current HLC code generator just completely ignore it which cause a breaking change between the track1 and track2 SDK about the client name for those RPs. As this extension is marked as deprecated in the document 
![image](https://user-images.githubusercontent.com/55688292/154188062-6e4a9fbb-497c-4ccc-872b-980db5b88cfb.png)
 Should we work on the code generator to support it ? Or to have some other workaround ?

**Comment by qiaozha** [comment]
@sarangan12  @ramya-rao-a Could you take a look at this issue? Thanks
/cc @lirenhe

**Comment by lirenhe** [comment]
@qiaozha, could you help to figure out this behaviour for other SDKs?

**Comment by sarangan12** [comment]
Looking at this issue now. Will update the issue shortly

**Comment by sarangan12** [comment]
1. In the [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) repository, there are 466 instances where this field of `x-ms-code-generation-settings` is used. 
2. As mentioned above, this extension is already marked as deprecated as mentioned [here](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#generic-extensions)
3. This extension is not supported in Autorest V3. If you try executing any swagger with this extension, you will get the following warning:
```
warning | OutdatedExtension | Semantic violation: Extension 'x-ms-code-generation-settings' is not supported in Autorest V3. It will just be ignored. (info > x-ms-code-generation-settings)
```
4. So, at this point, we cannot support this extension in our generator (since it is not supported by Autorest core itself and Autorest has made a conscious decision to stop supporting it)
5. That still leaves the question how do we support the swagger files with these extensions. My recommendation is during the migration we have to move the values (under `x-ms-code-generation-settings`) to configuration files (such as `readme.typescript.md`) so there will not be any breaking changes.

**Comment by qiaozha** [comment]
Thanks @sarangan12 for the investigation. I am fine with add those configuration in readme.typescript.md to avoid breaking change.

**Comment by sarangan12** [comment]
As there are no pending action items for this issue, I am resolving it.
