### ISSUE TITLE
[Mgmt] Add baseUrl customization for track2 SDK

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1337]
Currently we are using 
`baseUri: options.endpoint || "https://management.azure.com/" ` 
 in mgmt plane track2 SDK [track2 link](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/keyvault/arm-keyvault/src/keyVaultManagementClient.ts#L83). which is different from what we did in the [track1 SDK link](https://github.com/Azure/azure-sdk-for-js/blob/feature/v4/sdk/keyvault/arm-keyvault/src/keyVaultManagementClientContext.ts#L57)
`this.baseUri = options.baseUri || this.baseUri || "https://management.azure.com";`
I wonder why we remove the support of baseUri customization and use endpoint instead ?

customer suggest us to change it into 

`baseUri: options.endpoint ?? options.baseUri ?? "https://management.azure.com/"`

see original issue here https://github.com/Azure/azure-sdk-for-js/issues/20651

**Comment by qiaozha** [comment]
@sarangan12 and @joheredi do you have any comments about this issue ?

**Comment by joheredi** [comment]
It is unfortunate that we have `baseUri` in core-client's [ServiceClientOptions](https://github.com/Azure/azure-sdk-for-js/blob/3a5d82089d2458ed21c37c572142e80f3561e27b/sdk/core/core-client/src/serviceClient.ts#L33). As it stands right now I think this would be the right fix to do since we are providing an option that we are ignoring.

However, I wonder if we should mark baseUri as deprecated in core-client and replace it with `endpoint`? @xirzec, @bterlson what do you think?

Note: the generator generates an `endpoint` property and extends the `ServiceClientOptions` interface

**Comment by bterlson** [comment]
Having two properties for the same thing seems bad, but agree that step 1 in this situation is to make sure baseUri isn't ignored. The customer's fix makes sense to me (endpoint wins if it's set). Deprecating makes sense to me for longer term.  How did we end up with two properties for the same thing?

**Comment by qiaozha** [comment]
@bterlson  I guess this is probably because data plane is using endpoint since track1 and mgmt plane on the other hand is using baseUri. @joheredi feel free to correct me if I am wrong. Thanks

**Comment by joheredi** [comment]
@bterlson, I think `baseUri` was inherited from `core-http` and we didn't get rid of it 😞 in favor of endpoint. I think the way we can proceed right now is with 3 changes:

1. Fix the generated code so that it honors `baseUri`, as Brian mentioned, `endpoint` should win over `baseUri` if both are present.
2. Add `endpoint` to the ServiceClientOptions in `core-client` next to `baseUri`, also mark `baseUri` as deprecated to discourage users from using it, so that in the next major bump we take we can remove `baseUri`
3. Remove `endpoint` from the generated code as it extends ServiceClientOptions and would get `endpoint` from there

**Comment by qiaozha** [comment]
I think we can close this issue now as all the action items have been finished.
