### ISSUE TITLE
TypeError: js_yaml_1.Schema.create is not a function

### ISSUE THREAD

**Issue by Naethyn** [Azure/autorest.typescript#1866]
Error trying to generate an azure function in typescript from an open api specification.

**Command:** 
`autorest --azure-functions-typescript --input-file:swagger.json  --output-folder:./generated-azfunctions --no-namespace-folders:true --verbose --version:3.5.1`

**Error:**
/home/vscode/.autorest/@autorest_azure-functions-typescript@0.0.1-preview/node_modules/@azure-tools/codemodel/dist/model/yaml-schema.js:38
exports.codeModelSchema = js_yaml_1.Schema.create(js_yaml_1.DEFAULT_SAFE_SCHEMA, [
                                           ^

TypeError: js_yaml_1.Schema.create is not a function
    at Object.<anonymous> (/home/vscode/.autorest/@autorest_azure-functions-typescript@0.0.1-preview/node_modules/@azure-tools/codemodel/dist/model/yaml-schema.js:38:44)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/vscode/.autorest/@autorest_azure-functions-typescript@0.0.1-preview/node_modules/@azure-tools/codemodel/dist/exports.js:42:14)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)

**Comment by skipnz** [comment]
I'm having the same issue as above.

**Command:**

autorest --input-file:'./openapi.yaml' --version:3.0.6320 --azure-functions-typescript --no-namespace-folders:True --generate-metadata:false --output-folder:'./functions' --verbose

AutoRest code generation utility [cli version: 3.6.3; node: v16.20.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: 3.0.6320.
   Loading AutoRest core      '/home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/dist' (3.0.6320)
No configuration found at 'file:///srv/ftr-functions/'.
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/inspect.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/directives.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/pipeline.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/loader-openapi.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/miscellaneous.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/patches.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/plugin-powershell.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/plugin-azureresourceschema.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/plugin-csharp.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/plugin-go.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/plugin-java.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/plugin-nodejs.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/plugin-php.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/plugin-python.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/plugin-ruby.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/plugin-typescript.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/plugin-validators.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/plugin-az.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/plugin-trenton.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/plugin-azure-functions.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/graphs.md'
   Including configuration file 'file:///home/daniel/.autorest/@autorestcore@3.0.6320/nodemodules/@autorest/core/resources/help-configuration.md'
   Loading AutoRest extension '@autorest/azure-functions-typescript' (latest->0.0.1-preview)
   Including extension configuration file 'file:///home/daniel/.autorest/@autorestazure-functions-typescript@0.0.1-preview/nodemodules/@autorest/azure-functions-typescript/README.md'
   Loading AutoRest extension '@autorest/modelerfour' (4.15.396->4.15.396)
   Including extension configuration file 'file:///home/daniel/.autorest/@autorestmodelerfour@4.15.396/nodemodules/@autorest/modelerfour/readme.md'
/home/daniel/.autorest/@autorest_azure-functions-typescript@0.0.1-preview/node_modules/@azure-tools/codemodel/dist/model/yaml-schema.js:38
exports.codeModelSchema = js_yaml_1.Schema.create(js_yaml_1.DEFAULT_SAFE_SCHEMA, [
                                           ^

TypeError: js_yaml_1.Schema.create is not a function
    at Object.<anonymous> (/home/daniel/.autorest/@autorest_azure-functions-typescript@0.0.1-preview/node_modules/@azure-tools/codemodel/dist/model/yaml-schema.js:38:44)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/daniel/.autorest/@autorest_azure-functions-typescript@0.0.1-preview/node_modules/@azure-tools/codemodel/dist/exports.js:42:14)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
Process() cancelled due to failure

**Comment by qiaozha** [comment]
I think this issue belongs to this repo https://github.com/Azure/autorest.azure-functions-typescript

**Comment by aodgizmo** [comment]
Don't close this, it is still broken.

**Comment by pontusvision** [comment]
Broken for me also.
