### ISSUE TITLE
Interested in Using Autorest for a Custom SDK for Backstage

### ISSUE THREAD

**Issue by sennyeya** [Azure/autorest.typescript#1887]
Hi! I'm a maintainer for [Backstage](https://github.com/backstage/backstage) and we're interested in using Autorest to generate SDKs for our frontend plugins to communicate with our backend. 

Backstage uses a custom URL discovery service to discover the backend URL and also has a custom `fetch` service, examples [here](https://github.com/backstage/backstage/pull/17470/files#diff-65131825dccbd8c5fd1f312fed0cdc83835d8bdb5ebae404627fee58f0f5df3eR49). From what I can tell, this makes it very hard to adopt `autorest.typescript` as is due to use of `@azure/*` tooling across all 3 packages/layers (CADL -> TypeSpec -> Code).  We'd like to chat to see if it's possible to allow custom `ts-morph` output without forking all 3 packages.

Please let me know how we can get in contact.

**Comment by qiaozha** [comment]
If I am understanding it correctly, you want us to have a way to customize the output, so that you can use @autorest/typescript with an input of the OpenAPI spec here https://github.com/backstage/backstage/pull/17470/files#diff-0b3e4d2e58a312186c7fdd6bc6cdcd7afecf80db667eda61e8c7565216077551, then we render our output with the template you pass in the `packages/template-openapi-plugin-client/src/typescript-backstage/` to generate the customized output as you like here `packages/catalog-client/src/generated`?

**Comment by sennyeya** [comment]
Not quite, the work in the linked PR is to leverage `openapi-generator`. Ideally, we'd be able to use a language specific code generator like `ts-morph` instead of Handlebar templates. That's where we think `autorest` could fit in, converting `TypeSpec (or CADL not sure which is the intermediate) -> Typescript`, however, we're concerned that the current set of packages is heavily tied to the `@azure/*` ecosystem, see [this](https://github.com/Azure/autorest.typescript/blob/main/packages/autorest.typescript/src/generators/mappersGenerator.ts#L49), [this](https://github.com/Azure/autorest.typescript/blob/main/packages/rlc-common/src/buildClient.ts#L157), and [this](https://github.com/Azure/autorest.typescript/blob/main/packages/typespec-ts/src/modular/buildProjectFiles.ts#L124). We'd like to be able to create a single package, similar to `packages/autorest.typescript` in this repo that takes an intermediate representation of the API spec and converts it to a Typescript package, with full control of the output. As it is now, I think we'd have to fork the other 3 packages as the code generation logic sits in all 3. Please correct me if I'm misunderstanding how this repo is set up.

**Comment by qiaozha** [comment]
Is this what you wanted https://github.com/Azure/autorest.typescript/issues/1854 ?

**Comment by sennyeya** [comment]
I don't think so, that's focused -- I believe - on using the generic autorest output for use with a third party REST API. Our goal is to use autorests internal representation of the schema (CADL?) for use with a custom ts-morph implementation to create a completely custom typescript project.

**Comment by sennyeya** [comment]
@qiaozha bump on this, would it be possible to jump on a call?

**Comment by qiaozha** [comment]
I am afraid this is currently not in our plan, @xirzec any thoughts here ? But I feel like there's some gaps,
1. TypeSpec or CADL is API description language, you can consider it as OpenAPI.
2. we support two kinds of TypeScript clients generation, high level client [example](https://www.npmjs.com/package/@azure/arm-compute) and rest level client [example](https://www.npmjs.com/package/@azure-rest/arm-compute), 
3. In the high level client generation, currently we only support to generate it from swagger or OpenAPI, and in the rest level client generation, we support generate from both swagger or OpenAPI and TypeSpec or Cadl. 
4. Here's the high level work flow [link](https://github.com/Azure/autorest.typescript/blob/main/packages/autorest.typescript/CONTRIBUTING.md#typescriptjavascript-high-level-client-sdk-generator-design) and here's the rest level work flow [link](https://github.com/Azure/autorest.typescript/blob/main/docs/RLC-generation-Design.md)
5. If I am understanding correctly, you are asking us to export the intermediate model of high level client for you to customize ?  basically just the result of transformCodeModel [here](https://github.com/Azure/autorest.typescript/blob/main/packages/autorest.typescript/src/typescriptGenerator.ts#L72C9-L72C22) 

As currently we put a lot of effort in the RLC and TypeSpec, I am afraid I can not help you in a short time.

**Comment by sennyeya** [comment]
> I am afraid this is currently not in our plan, @xirzec any thoughts here ? But I feel like there's some gaps,
>  1.  TypeSpec or CADL is API description language, you can consider it as a superset of OpenAPI.

Yup, I think I meant CodeModel which is the Autorest intermediate language.

> 5. If I am understanding correctly, you are asking us to export the intermediate model of high level client for you to customize ? basically just the result of transformCodeModel [here](https://github.com/Azure/autorest.typescript/blob/main/packages/autorest.typescript/src/typescriptGenerator.ts#L72C9-L72C22)

Aha yup, I'd missed that initially. Would that be possible? I think that would be enough to allow us to create a custom high-level client.

> As currently we put a lot of effort in the RLC and TypeSpec, I am afraid I can not help you in a short time.

Could this be something I contribute? Happy to do the heavy lifting here.

**Comment by xirzec** [comment]
@sennyeya to confirm, are you interested in generating clients in multiple languages or only in TS/JS?

I also wanted to clarify a few points:

1. CADL is an older name for TypeSpec. They are the same thing, just rebranded.
2. AutoRest isn't necessary for use with TypeSpec as TypeSpec has its own concept of emitter frameworks.
3. We're not currently staffed to solve the general problem of building clients for arbitrary RESTful services and we already have a considerable backlog of work to build clients for Azure hosted services.

A bit of history here: AutoRest has existed for a while (I think it started in 2016?) and generally is an OpenAPI 2.x to client generator with many language plugins. The greatest limitation it has is based on what OpenAPI supports and since it was built around 2.x, many of the conveniences added in 3.x can't be used with our generator plugins. We also added several `x-ms-` custom properties to support various Azure patterns, but there was still a fair amount of magic to map from "here is a bunch of routes" to "these are operations on service clients". Some of this magic was by convention, like operation groups being inferred by the way you name `operationId`s.

TypeSpec is comparatively new (though it existed conceptually in various forms since 2020 or so) and attempts to tackle the service descriptor problem by reversing the approach of how you author service contracts. Rather than being a serialization of what HTTP endpoints your server is exposing, it offers primitives that let you describe remote operations and the shape of their inputs and outputs. This isn't intrinsically tied to one transport (HTTP) or representation (JSON/XML), though of course you can use it with those technologies.

The idea is that TypeSpec describes at a high level what information is transmitted and received to a service and from this you can generate clients and service endpoints to concretely implement that contract.

What this means for us is that we're in the middle of a transition away from writing OpenAPI documents and instead writing TypeSpec files (tsp). Since we already have client plugins for AutoRest for many languages, the approach many plugin maintainers have taken (including this one!) is to abstract ourselves from the AutoRest codemodel and create a TypeSpec emitter that can emit this new intermediate format.

For this repo, this currently takes the form of [RLCModel](https://github.com/Azure/autorest.typescript/blob/9b743cfdd6428fac0f321bd8e08ecdee88156ff0/packages/rlc-common/src/interfaces.ts#L3). You can imagine in the future perhaps AutoRest isn't necessary as we fully migrate off of OpenAPI as the source of truth.

While it's possible there is some overlap with how we're assembling clients for Azure services, I'm not sure how much of what we're trying to build is going to resemble what you have in mind for your scenario. I think you may be better served by implementing your own TypeSpec emitter using the Emitter framework and ts-morph: https://microsoft.github.io/typespec/extending-typespec/emitter-framework

**Comment by sennyeya** [comment]
@xirzec Thanks for the in depth response! Interesting slice of history.

>  are you interested in generating clients in multiple languages or only in TS/JS?

It would just be TS/JS generation. 

> CADL is an older name for TypeSpec. They are the same thing, just rebranded.

Thanks for the clarification, this was pretty confusing reading through the documentation and code. 

> I think you may be better served by implementing your own TypeSpec emitter using the Emitter framework and ts-morph: https://microsoft.github.io/typespec/extending-typespec/emitter-framework

We're committed to using OpenAPI 3, so adopting TypeSpec alone wouldn't be possible for us at the moment. Would it be possible to convert OA3 -> TypeSpec -> generator? 

I really appreciate you taking the time to write all of this up! Lot of learning on my side.

**Comment by xirzec** [comment]
> We're committed to using OpenAPI 3, so adopting TypeSpec alone wouldn't be possible for us at the moment. Would it be possible to convert OA3 -> TypeSpec -> generator?

One of the major motivations behind TypeSpec was to have the API description support better projections into higher level languages than what we were able to do with heuristics and special properties in OpenAPI. 

My understanding is that there are certain types of operations/relationships that can't be modeled in OpenAPI in the same way as TypeSpec (such as using [spread](https://microsoft.github.io/typespec/language-basics/models#spread) for composition.) We do, however, support going the other direction and [generating OpenAPI from TypeSpec](https://github.com/microsoft/typespec/tree/main/packages/openapi3).

I think this is going to be the eventual sticking point on collaboration though, if you are OpenAPI 3 first and we are optimizing towards generating primarily from TypeSpec with OpenAPI 2 being a legacy input. 

There is another project that I recently heard about that might be better aligned with what you are trying to do: https://github.com/microsoft/kiota -- I haven't tried it out personally, but perhaps it would be worth reaching out via a GitHub issue?

**Comment by sennyeya** [comment]
Yeah, that makes sense. We are looking to maybe use another tool called Fern, https://buildwithfern.com/docs/comparison-with-openapi that have their own superset of OpenAPI language. There's clearly a number of gaps with OA3 that for some of the base cases you're describing OA4 seems to address, https://github.com/OAI/moonwalk. 

Thanks for the link to Kiota, will definitely reach out to them! Again, thanks for the help on this, I really appreciate it!
