### ISSUE TITLE
Enum ignores value type

### ISSUE THREAD

**Issue by heycalmdown** [Azure/autorest.typescript#1951]
Although the TypeSpec syntax supports the value type such as string, integer, and float, `typespec-ts` only emits strings for enum types.

```typespec
enum IntegerEnum {
  One: 1,
  Two: 2,
  Three: 3,
}

enum StringEnum {
  One: "1",
  Two: "2",
  Three: "3",
}

enum FloatEnum {
  One: 1.0,
  Two: 2.0,
  Three: 3.0,
}

model Result {
  int: IntegerEnum,
  float: FloatEnum,
  str: StringEnum,
}

@service({})
namespace Test {
  op get(): Result;
}
```

```ts
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

export interface ResultOutput {
  /** Possible values: 1, 2, 3 */
  int: string;
  /** Possible values: 1, 2, 3 */
  float: string;
  /** Possible values: 1, 2, 3 */
  str: string;
}
```

**Comment by MaryGao** [comment]
@heycalmdown This is by design for `typespec-ts` emitter because in Azure we assume the enum by default could be extensible. You could add the `@fixed` decorator([refer](https://azure.github.io/typespec-azure/docs/libraries/azure-core/reference/decorators#@Azure.Core.fixed)) and see [example here](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAYXp1cmUtdG9vbHMvdHlwZXNwZWMtxhVjb3JlIjsNCg0KdXNpbmcgQcQWLkNvcmXFFUBmaXhlZA0KZW51bSBJbnRlZ2VyRcQMew0KICBPbmU6IDEsxAtUd286IDLGC2hyZWU6IDMsDQp90URTdHJpbmfPQyIxIspFIjLHDcZHIjPED9JJRmxvYXTPSDEuMMpIMsgNxkgzxQ%2FFSG1vZGVsIFJlc3VsdMY%2BaW50OuwA38U5ZsRiOsppxRVzdHI66wDFyFNAc2VydmljZSh7fSkNCm5hbWVzcGFjZSBUZXPHY29wIGdldCgpOsd5Ow0KfQ%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D).

**Comment by heycalmdown** [comment]
Oh, I've never included `typespec-azure-core`. let me try..

<img width="463" alt="image" src="https://github.com/Azure/autorest.typescript/assets/154198/b5cb03f6-74a5-4759-bfa7-bf8cd518d1b6">

is it okay?

**Comment by MaryGao** [comment]
Yes, I think this is just warnings

**Comment by heycalmdown** [comment]
I understand that `typespec-ts` is a part of `@azure-tools`, but as a TypeSpec user outside of Azure eco-system, I'm not relying on `typespec-azure-core` except `@fixed`. Is there any chance to write the decorator(`@fixed`) by hand?

(importing `@azure-tools/typespec-azure-core` requires too many lint rules even they're warnings. Too many warnings..)

**Comment by MaryGao** [comment]
Understood, another workaround is leveraging the union features and this would result in the same typescript code.

```
alias IntegerUnion = 1 | 2 | 3;
alias StringUnion = "1" | "2" | "3";
alias FloatUnion = 1.0 | 1.1 | 2.1;

model Result {
  int: IntegerUnion,
  float: StringUnion,
  str: FloatUnion,
}

@service({})
namespace Test {
  op get(): Result;
}
```

**Comment by heycalmdown** [comment]
Since I can't take the approach for my purpose, but thank you providing the workaround. Good to know that.

**Comment by qiaozha** [comment]
we have released a new version of emitter, this problem should have been addressed.
