### ISSUE TITLE
Support decimal type from typespec

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2157]
https://github.com/Azure/azure-rest-api-specs-pr/pull/13119#discussion_r1376998182

In typespec, we have `decimal` and `decimal128`. And in health insight we have [decimal type used](https://github.com/Azure/azure-rest-api-specs-pr/blob/d0af087407c0f4ee2ce49a9f51d26ad580d8e616/specification/cognitiveservices/HealthInsights/HealthInsights.Common/model.common.fhir.elements.tsp#L178C1-L179C19). 

```
  @doc("Numerical value (with implicit precision)")
  value?: decimal;
```

https://microsoft.github.io/typespec/language-basics/built-in-types#numeric-types

TypeSpec definition for decimal:

```
/**
 * A decimal number with any length and precision. This represent any `decimal` value possible.
 * It is commonly represented as `BigDecimal` in some languages.
 */
scalar decimal extends numeric;

/**
 * A 128-bit decimal number.
 */
scalar decimal128 extends decimal;
```

We need to decide on how to support this type in both RLC and Modular.

**Comment by xirzec** [comment]
How is this being represented over the wire? Presumably they are not sending it as a JSON number since that would potentially lose precision. If it's a string my preference is to keep it as a string and let the consumer use whatever userland library they prefer to handle the number manipulation.

**Comment by MaryGao** [comment]
Using @encode as string to preserve decimal's precision could be our recommandation. But I may have two concerns:
- Java/.Net/Python have the native support for decimal, not sure it is a good idea to suggest that for JS
- Service team may follow an external specification and we have no choice to encode them as string e.g health insight follows the [FHIR standard quantity model](https://www.hl7.org/fhir/R4/datatypes.html#Quantity) and [discussion here](https://github.com/Azure/azure-rest-api-specs-pr/pull/13119#discussion_r1377135364). 

I agree that for calculations, users could pick their own lib then converting to a number or string for us(aka client SDK) and within the safe range it should be SAFE also.

However I am worrying about this has potential risks but it is a silent process. 

Not sure we need to involve more communications with service team to clarify this because eventually they will take the cost.

On the other hand how to educate end users that the contact with server side is based on `decimal` so you may pick your own decimal lib for any calculations. And we expect `0.2 + 0.1 = 0.3` not `0.30000000000000004`.

**Comment by MaryGao** [comment]
pls ignore the wrong linked to lro epic :)

**Comment by bterlson** [comment]
To be explicit, there are two risks related to precision loss:

1. Precision loss from conversion from the wire in languages like JavaScript that have insufficient precision in the only data type available to represent numbers.
2. Precision loss from customer code using mathematical operations on floats.

For 1, the damage is limited to JavaScript as I believe most other languages have the ability to either dynamically choose an appropriate data type or specify the data type when parsing number literals from JSON. For JS in particular, the risk of 1 seems very low considering I have not seen a use case in Azure yet where numbers would fall outside the range of a double, which isn't particularly surprising given that the main usecase is currency amounts, and currency amounts above 2^53-1 or outside the precision of floats for typical currency values (~15 decimal places) seems very unlikely. However, services should be aware of these limitations and  use @encode properly, documenting this somewhere for service teams seems good.

For 2, again the damage is mostly limited to JavaScript, since other languages can presumably vend a decimal appropriately regardless of how the decimal is placed on the wire. For JavaScript in particular, the risk seems low considering that the use cases I examined didn't involve round trip of currency values that are calculated by the client. However, it would probably be a good idea to document fields with the decimal type with some standard verbiage explaining that it's a decimal value and to take care when doing math on the value to avoid precision loss.
