### ISSUE TITLE
Default endpoint and credentialScope setting for ARM is missing

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2349]

**Comment by joheredi** [comment]
@MaryGao can you please add details to this issue?

What's the current behavior vs what Track2 had

**Comment by joheredi** [comment]
I think this is related to https://github.com/Azure/autorest.typescript/issues/2353

These defaults should really come from the TypeSpec ARM Templates.

Note endpoint seems to be set correct


![Image](https://github.com/Azure/autorest.typescript/assets/21109913/63be1e55-b0a4-46e1-8cec-1ce750dcb5b0)

**Comment by joheredi** [comment]
Ideally this should be fixed in the Arm Template, however I'll be open to special case this for Flavor Azure + Arm

**Breaking Change Categorization**
Bug (Unwanted Breaking Changes):

- [ ] Missing data from the spec in the new implementation.
- [ ] Incorrect results produced by the new implementation.
- [ ] Slight differences in the new implementation that do not improve user experience. If uncertain, categorize as unwanted.

Improvements (Acceptable Breaking Changes):

- [ ] Fixes broken behavior in the new implementation.
- [ ] Offers clear enhancements to user experience.
- [ ] Eliminates or discourages bad patterns.
- [ ] Provides additional functionality.
- [ ] Aligns more closely with TypeSpec standards.

**Comment by MaryGao** [comment]
this should be fixed in latest generation for [endpoint](https://github.com/Azure/autorest.typescript/pull/2536/files#r1610826131) and credentialScop is tracked in another issue.
