### ISSUE TITLE
Operation group interface is changed from DataProducts to DataProductsOperations

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2351]

**Comment by qiaozha** [comment]
pending https://github.com/Azure/autorest.typescript/pull/2387 to mitigate the gap here.

**Comment by MaryGao** [comment]
Could you also consider this case? https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/monitor/arm-monitor/src/monitorClient.ts#L368

**Comment by qiaozha** [comment]
For TypeSpec like:
```
interface Metrics {
  ...op definitions
}
```

In HLC, we use operation group name itself as the operation group interface name, 
```ts
export interface Metrics {
  ...op definition
}
```
in client class definition, we have 
```ts
class MonitorClient {
  // ... other client related definitions
  metrics: Metrics
  // ... other operation groups properties
}
```
And because we need to export all the operation group interfaces and all the models, there's no validation rule to make sure they can not be the same, what HLC will do is to rename the operation group interfaces with an `Operations` suffix.

```ts
export interface MetricsOperations {
  ...op definition
}
```

And this change also applies to the client class property 
```ts
class MonitorClient {
  // ... other client related definitions
  metricsOperations: MetricsOperations
  // ... other operation groups properties
}
```

But in current Modular implementation, we add `Operations` suffix no matter if there's any conflicts. 
```ts
export interface MetricsOperations {
  ...op definition
}
```
in client class definition, we have 
```ts
class MonitorClient {
  // ... other client related definitions
  metrics: MetricsOperations
  // ... other operation groups properties
}
```

Breaking summary for accepting the current Modular implementation:
1. OperationGroupInterface change for non-conflict operation groups
    AlertRules => AlertRulesOperations

2. User experience change for conflicted operation groups
    HLC. client.metricsOperations.create();
    Modular client.metrics.create();

Prefer to keep the current Modular behavior and accept the breaking change because:
1. It's not a quite common way to use the operation group interface name directly.
2. the current HLC user experience is not a happy one.
3. In previous HLC, we sometimes found when service team add a model whose name conflicts with the previous existing operation group, we have to breaking the SDK because of our own codegen design limitation.

**Comment by qiaozha** [comment]
We will accept the operation group interface name breaking, and try to use `@clientName` to mitigate the user experience breaking.

**Comment by joheredi** [comment]
@qiaozha it looks like we reached an agreement here, can we close this issue?

**Comment by qiaozha** [comment]
since we have reviewed this, I am fine to close it.
