### ISSUE TITLE
Modular doesn't include response headers in the result type

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#2360]
There's a breaking change between modular and hlc:
Removed model ```XXXResponse```

Description:
For HLC, codegen will use a unique model for a non-paging operation as the response model, for example:
If we call dataproducts.beginCreateAndWait() function from networkanalytics package.
the response is promised as [DataProductsCreateResponse](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/networkanalytics/arm-networkanalytics/src/operationsInterfaces/dataProducts.ts#L93-L98)
and in model definitions, it is defined in [here](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/networkanalytics/arm-networkanalytics/src/models/index.ts#L922)

but for modular, the generated code remove the DataProductsCreateResponse model and just use [DataProducts ](https://github.com/v-jiaodi/autorest.typescript/blob/sync-lro-modular-support/packages/typespec-test/test/NetworkAnalytics.Management/generated/typespec-ts/src/classic/dataProducts/index.ts#L51)as the response model

**Comment by kazrael2119** [comment]
link to https://github.com/Azure/autorest.typescript/issues/2308#issuecomment-1999201392

**Comment by joheredi** [comment]
I dug deeper into this and seems like we want to fix this as we are missing bringing headers into the response in Modular.

This is what Track2 has 



![Image](https://github.com/Azure/autorest.typescript/assets/21109913/8662c2d5-d729-4173-a820-d787263bccbe)


![Image](https://github.com/Azure/autorest.typescript/assets/21109913/4efddc9a-31a5-4537-aea6-f4baa0f16986)


![Image](https://github.com/Azure/autorest.typescript/assets/21109913/aed34208-08ea-40c8-8b8b-17b8eb4ea305)


![Image](https://github.com/Azure/autorest.typescript/assets/21109913/0a2cee90-4cb6-4e21-9885-0b46a6ea292f)



This is what Modular would generate:



![Image](https://github.com/Azure/autorest.typescript/assets/21109913/0aca8727-0d4d-4ac8-8dc3-1d1559af9c53)

![Image](https://github.com/Azure/autorest.typescript/assets/21109913/bf30bdc0-9ed3-4bba-9261-7c9dcf1e9919)


So this is an unwanted breaking change and should be fixed in a similar fashion as T2 by creating a Response interface that is the intersection of the current thing plus the operation response headers

**Comment by joheredi** [comment]
Updating the title

**Comment by joheredi** [comment]
**Breaking Change Categorization**
Bug (Unwanted Breaking Changes):

- [ ] Missing data from the spec in the new implementation.
- [x] Incorrect results produced by the new implementation.
- [ ] Slight differences in the new implementation that do not improve user experience. If uncertain, categorize as unwanted.

Improvements (Acceptable Breaking Changes):

- [ ] Fixes broken behavior in the new implementation.
- [ ] Offers clear enhancements to user experience.
- [ ] Eliminates or discourages bad patterns.
- [ ] Provides additional functionality.
- [ ] Aligns more closely with TypeSpec standards.

**Comment by qiaozha** [comment]
we accept the breaking for both the response type and headers.
