### ISSUE TITLE
[Modular] Log warning/error for `This client do not support client api-version`

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2427]
The existing hlc is behaving to have api version customized in the operation level if there's any operations that don't have api version parameter, which is consistent with the current modular implementation from user experience perspective.

We don't want to change behavior here, but want to introduce a warning to let customers know that the api-version they have set is being ignored.

**Comment by lmazuel** [comment]
Only necessary work in versioning right now is limited to the JS guidelines:
https://azure.github.io/azure-sdk/typescript_design.html#ts-service-versions

![image](https://github.com/Azure/autorest.typescript/assets/1050156/4cb12ed1-b564-48c1-9f46-5be7d4f6769b)

Which from a TypeSpec perspective, is just consuming the enum of api version, and that's it.

"Basic versionning" must NOT include any work on `@add` or other versionning decorators

**Comment by joheredi** [comment]
The actual requirement is that the API version can be overridable in the client constructor. However, the test implemented in PR #2457 attempts to override the API version through operation parameters, which does not meet the specified requirement.

I tried modifying the test as shown in this screenshot, which should meet the requirement:

![Modified Test Screenshot](https://github.com/Azure/autorest.typescript/assets/21109913/36bb67ee-22f7-40c4-9fea-33eeeade43dc)

While the modification compiles correctly, it fails to apply the specified API version. This issue arises because the API version provided to the client is not being accounted for, and the default API version is applied instead if none is specified in the operation.

![Issue Demonstration Screenshot](https://github.com/Azure/autorest.typescript/assets/21109913/bb352565-857f-4f52-98cf-6a31dfc460a6)

To address this, we need a method to prioritize the API version sources as follows:
1. API version specified in the operation
2. API version specified in the client
3. Default API version

This requires making the `apiVersion` from `clientOptions` accessible to the operations. I see a couple of potential solutions:

**Option 1: Introduce a Symbol in `clientContext` for `apiVersion`.**
   - **Pros:** May only require changes to code generation, and provides a straightforward approach without additional indirection.
   - **Cons:** Could necessitate the use of type casting (e.g., `any` cast) both when inserting and retrieving the symbol, albeit only internally.

**Option 2: Enable the `ApiVersion` Pipeline Policy.**
   - **Pros:** Utilizes the existing `ApiVersion` policy infrastructure.
   - **Cons:** Adds some indirection, complicating the logic for operation-level API version handling. We might still need to access `clientOptions.apiVersion` from the context to decide whether a default value should be applied. Implementation might also require type casting when constructing operation query parameters, as `apiVersion` will be mandatory but could be `undefined` if managed by the policy.

I am inclined to recommend the first option for its simplicity and direct approach. However, I welcome other perspectives and am open to discussing alternative solutions.

**Comment by qiaozha** [comment]
In https://github.com/Azure/autorest.typescript/issues/2212#issuecomment-1996269697 we have discussed when to move api version to client level, and we have agreed only to allow client side api version if all the operations have api version.  And cadl ranch's case, because there's an operation https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/server/versions/versioned/main.tsp#L44-L48 that specifically asked us to not contain any api version there, It's expected to not move the api version in the client side. and we also removed the apiVersionPolicy here https://github.com/Azure/autorest.typescript/blob/main/packages/typespec-ts/test/modularIntegration/generated/server/versions/versioned/src/rest/versionedClient.ts#L36 to make sure we don't append any apiVersion unnecessarily. 
Therefore, we have to customize this apiVersion in the operation level in Laurent's case, if it's a case that every operations have a apiVersion in the query, we can certainly customized it in the client level.

**Comment by lmazuel** [comment]
I think we're all on the same page to say that if all operations have an api-version, then it must be configurable at the client level. This is a track2 requirement: https://azure.github.io/azure-sdk/typescript_design.html#ts-service-versions

Now, what if only a few operations have api-version? I think I will let your team and architects decide what makes sense for your language, I'm not prescriptive of having it in the client. I would just add a comment in your test base around this test, for clarity in the future.

A few requirements though:
- If an operation do not take it, it's a problem add the query parameter anyway. Never send more than necessary.
- If specifying it in the client is possible, but it's silently ignored, it's confusing for customers. Either you accept it and you use it, or you don't accept it.

**Comment by qiaozha** [comment]
@joheredi  I found the existing hlc is behaving to not have api version customized in the operation level if there's any operations that don't have api version parameter, which is consistent with the current modular implementation from user experience perspective. I would say, we should not change this behavior ? 

For @lmazuel 's concern of client level apiVersion exists but being silently ignored, Do you think we should consider to remove the client level api version from core [ClientOptions](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/core-client-rest/src/common.ts#L331) and generate it in each client? I think in this way, we don't need to change anything in the [apiVersion policy](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/core-client-rest/src/apiVersionPolicy.ts#L14) here?

**Comment by lmazuel** [comment]
Reading your message @qiaozha , if this is a core type, accepting it but raising an exception with a meaningful error like "This client do not support client api-version, please change it at the operation level" works for me as well. Maybe it's easier for you that way.

**Comment by joheredi** [comment]
We may also consider instead of throwing, logging a warning.

**Comment by qiaozha** [comment]
I am fine with log a warning.
