### ISSUE TITLE
Should generate as interface not record for empty named model with additional properties

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2535]
For typespec [definition ](https://github.com/Azure/typespec-azure/blob/bb338afd7c124c586d4c105475cdb3da1b216b17/packages/typespec-azure-resource-manager/lib/common-types/managed-identity.tsp#L33-L37) we will generate `Record<string, XXX>` for `UserAssignedIdentities` empty named model with additional properties. But I think we should generate a model with name UserAssignedIdentities.
 
```
model ManagedServiceIdentity {
  // ...
  @doc("The identities assigned to this resource by the user.")
  userAssignedIdentities?: UserAssignedIdentities;
}

/** The set of user assigned identities associated with the resource. The userAssignedIdentities dictionary keys will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}. The dictionary values can be empty objects ({}) in requests.", */
model UserAssignedIdentities is Record<UserAssignedIdentity>;
```

And should be generated as 

```ts
export interface UserAssignedIdentities extends Record<string, UserAssignedIdentity> {
}

```

**Comment by kazrael2119** [comment]
new case：

<img width="419" height="187" alt="Image" src="https://github.com/user-attachments/assets/fc7d1f7c-2a91-4d53-b6f8-3b27307f556b" />

<img width="397" height="240" alt="Image" src="https://github.com/user-attachments/assets/e1689b5d-c700-433e-9e0d-5fac3b8fb3a2" />

this is because using arm model insteasd of customized model.
