### ISSUE TITLE
Add check that packages contain required files before packing

### ISSUE THREAD

**Issue by ghost** [Azure/autorest.typescript#398]
Required files:
- README.md
- package.json
- LICENSE.txt

**Comment by joheredi** [comment]
We may want to add this step in the pre-pack step

**Comment by ramya-rao-a** [comment]
@joheredi, @sarangan12 Is this to test that these files are generated by the code generator or to test that the test to do so should be included in one of the generated npm scripts?

If it is the former, then don't we have unit tests in this project to test that these files are generated?

**Comment by joheredi** [comment]
I think this is referring to generating a check for those files so that the generated sdk has a `npm prepack` script that checks for this.

I'm not sure how much value this adds though, this seems to be very specific depending on where the SDK would live. And having this may be very opinionated on our side.

For example, in azure-sdk-for-js a lint rule is used to verify this. Other repos may be using different approaches
