### ISSUE TITLE
Async/Await errors not working as expected

### ISSUE THREAD

**Issue by shaunnez** [Azure/autorest.typescript#463]
Hello,

I have a API (POST) which returns 204 status code on success, or a 404 / 500 error code if there is an error.

This API is surrounded by a try / catch await call like below

try {
   await api.doYourThing(requestBody);
} catch(ex) {
   console.log('do something with ex')
}

IF the API returns a 422, then it is not going into the catch as expected.

Looking at the generated API from swagger (in summary its code is)...
```
        responses: {
          204: {},
          404: {},
          500: {},
          default: {}
        },
        serializer: this.serializer
      });
    } catch (err) {
      return Promise.reject(err);
    }
    return Promise.resolve(operationRes);
  }
```

How can I make it so that anything thats not a 200 / 204 status code is regarded as an error at the service level? 

The SWAGGER has the response defined as below
```

"responses": {
"204": {
"description": "Success"
},
"404": {
"description": "Not Found"
},
"500": {
"description": "Server Error"
}
}

```

I don't really want to override the http client.

**Comment by shaunnez** [comment]
Note: I'm using the "shortened" version of the generated code 

e.g.

service.someApi(data);

Not the following

service.someApiWithHttpOperationResponse

If i use the one with httpOperationRespones I can check for specific error codes, but it doesn't feel quite right.

**Comment by amarzavery** [comment]
The structure of the response will not change for 404 or a 500. Erorr message will be different. Hence,
 "default" is used for defining the schema for Error. 

By removing the negative response codes "404" and "500" from your swagger spec you can achieve the desired behavior.

**Comment by shaunnez** [comment]
Before I go removing an error message from swagger, what if I want to handle a 404 or 500 differently? What if I want to capture that error message?

Shouldn't the default response be that for a "error status code" that the promise is rejected? Currently, the promise is resolved and I have no way of getting the error code, let alone the error message

**Comment by amarzavery** [comment]
I am not sure if I was clear enough. To be sure, we are on the same page, 

**can you please provide a snapshot of the responses section of the operation object from your swagger spec?**

> Shouldn't the default response be that for a "error status code" that the promise is rejected? Currently, the promise is resolved and I have no way of getting the error code, let alone the error message

**If you define a "default" response status code with a proper schema for the `Error` then Autorest will honor that and reject a Promise with an Error of that schema/type** _with some caveat as explained below._


As per the [swagger specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responses-object), the spec author is supposed to describe at least one positive response code and a default for any errors We do support that. For example 
- if you define positive status codes like `200`, `201`, `202` and a `default` then any response code apart from `200`, `201`, `202` will be treated as an `Error` and will be deserialized based on the schema specified by the `default` status code..
- if you do define other status codes like `404`, `400`, `500`, apart from the positive status codes like `200`, `201`, etc. then Autorest will not treat them as error codes. In fact, the return type of your method will be the union of the schemas of all the defined status codes.
- When an error is thrown we do add a property called [`statusCode`](https://github.com/Azure/ms-rest-js/blob/master/lib/policies/deserializationPolicy.ts#L118) to the error object which is the response status code. [`error.body` is the deserialized body if a schema was provided for default](https://github.com/Azure/ms-rest-js/blob/master/lib/policies/deserializationPolicy.ts#L155).

> what if I want to handle a 404 or 500 differently? What if I want to capture that error message?

Above explanation is the default behavior. However, we do understand that users may want to specify negative response codes and would have a case where they want to handle each of them differently.. For that we have an extension called `"x-ms-error-response": true`. Take a look at this [sample swagger spec](https://github.com/Azure/autorest.testserver/blob/master/swagger/xms-error-responses.json#L94) and the [corresponding generated code](https://github.com/Azure/autorest.typescript/blob/master/test/vanilla/generated/XMSErrorResponses/operations/petOperations.ts#L123).

**NOTE: I think the TypeScript generator as of now, does not honor this extension. It will still treat `500` as an [expected status code logic defined in the deserialization policy in the runtime](https://github.com/Azure/ms-rest-js/blob/master/lib/policies/deserializationPolicy.ts#L109) and resolve the promise. This bug should be fixed.**

@daviwil  @ramya-rao-a 
This should be a simple fix in the generator and the underlying runtime (ms-rest-js).
- **Generator changes**: Autorest modeler should be giving us the information whether `x-ms-error-response: true` was provided for a given response status code. We need to add a new property (something like `"isErrorResponse": true  | false`) in the response section of the operation spec. For example over [here](https://github.com/Azure/autorest.typescript/blob/master/test/vanilla/generated/XMSErrorResponses/operations/petOperations.ts#L134). `500: { bodyMapper: Mappers.PetActionError, isErrorResponse: true },`
- **Runtime changes**: Then in the deserialization policy in the runtime(ms-rest-js) check for the property `isErrorResponse` while deserializing an expected status code.  If `true` then pretty much follow the [same steps that we are doing for processing `default` status code and reject the Promise with the deserialized Error](https://github.com/Azure/ms-rest-js/blob/master/lib/policies/deserializationPolicy.ts#L111-L161) instead of deserializing it as an expected response.
- In this [generator acceptance test](https://github.com/Azure/autorest.typescript/blob/master/test/vanilla/xmsErrorResponsesTests.ts#L17) we should assert that the promise is being rejected with right error message..

**Comment by joheredi** [comment]
I'm closing this issue since it hasn't had activity in a long time please reactivate if you need more clarification. 

x-ms-error-response should be handled now by v6 generator
