### ISSUE TITLE
Azure SDK baseUri always defaults to the ARM endpoint

### ISSUE THREAD

**Issue by willmtemple** [Azure/autorest.typescript#545]
In the current generated data-plane libraries, a bug makes it required to pass a `baseUri` in the options bag when it should be optional.

For example, see: https://github.com/Azure/azure-sdk-for-js/issues/6634

The issue is that in the client context class (which inherits from `AzureServiceClient`) constructor, a line like the following is generated:

```ts
this.baseUri = options.baseUri || this.baseUri || "https://graph.windows.net";
```

However, `AzureServiceClient` will _always_ initialize `this.baseUri` in its constructor to be the endpoint of the Azure Resource Manager, meaning that if `baseUri` is omitted from the options bag, then the default value will be "https://management.azure.com" (or whatever the ARM endpoint is in the current Azure Environment). So, for example, on the public Azure Cloud, if the service's endpoint is not "https://management.azure.com/", then subsequent REST requests will fail with an unhelpful error message:

`The request did not have a subscription or a valid tenant level resource provider.`

CC @daviwil

**Comment by willmtemple** [comment]
Code paths indicate that this will manifest as a bug in the following azure-sdk-for-js packages:

- `@azure/cognitiveservices-localsearch`
- `@azure/applicationinsights-query`
- `@azure/graph`
- `@azure/loganalytics`

**Comment by joheredi** [comment]
Thanks for bringing this up @willmtemple. This problem should be fixed in autorest.typescript v5. It can be used by adding the flag  `--use=@microsoft.azure/autorest.typescript@5.0.2` when running autorest

With v5, the client would use core-http instead of msRest, and the context class would extend `coreHttp.ServiceClient` directly which [doesn't initialize baseUri](https://github.com/Azure/azure-sdk-for-js/blob/b5ce9e75ce9fe80b24626d52d75fd09839e19e28/sdk/core/core-http/lib/serviceClient.ts#L178)

It would look similar to [this ](https://github.com/Azure/azure-sdk-for-js/blob/386696d8396634959cd72c8467d97971d09241e9/sdk/textanalytics/ai-text-analytics/src/generated/textAnalyticsClientContext.ts#L16)

I think Azure/azure-sdk-for-js/pull/6905 is a good fix to get unblocked quickly, but the longterm one should be to regenerate the API with v5.

Let me know if you have any questions and I'll be happy to discuss
