### ISSUE TITLE
[v6] Move LRO files into a package

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#613]
LRO needs to do runtime discovery to handle operations. Because of this, all the LRO files are being copied to each generated SDK.

Since the files would be the same it would make sense to move them to a separate package, or maybe even splitting it into a few different packages.

We need to discuss how to best organize this in packages.

Some ideas/notes:

* LROPolicy as @chradek mentioned in PR #611 may be a good candidate to live in core-http next to other policies. However since this LRO Policy is very Azure specific does it make sense to have it in core-http? 

* LRO Poller and operation, we could have this in core-lro however as the point above this is too azure specific, would that be a problem?

* If this is too specific for azure would it make sense to have a AzureUtilities package specifically for autorest?

**Comment by joheredi** [comment]
We should probably use @azure/core-client

**Comment by joheredi** [comment]
We can use this package https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/core/core-client

**Comment by joheredi** [comment]
We may want to move these packages when the move to core v2 happens

**Comment by sarangan12** [comment]
After a recent discussion with Deya, he is booked for this month. So, Assigning this task to myself.

**Comment by deyaaeldeen** [comment]
@sarangan12 thanks for taking on it! My approach for this issue would be to make core-lro export [LROPoller](https://github.com/Azure/autorest.typescript/blob/056566065dd8387ec2c928d5766c3d7f72b4f6c1/src/lro/lroPoller.ts#L20). On the other hand, I am hesitant to export `shouldDeserializeLRO` from core-lro because I never really took a closer look at this function and I wonder if we can get rid of it. I would prefer if we keep `shouldDeserializeLRO` as an implementation detail in code gen somehow but I am not sure how to do so.

**Comment by deyaaeldeen** [comment]
@sarangan12 I reassigned this issue to me because I was told we should not depend on core-client in core-lro and it is not straightforward to abstract core-client away in the lro files. I have an idea and hopefully will get it done in the July milestone.
