### ISSUE TITLE
Eslint warning in generated code

### ISSUE THREAD

**Issue by btmorr** [Azure/autorest.typescript#669]
I'm using autorest in a Typescript project with create-react-app. Unfortunately, create-react-app has decided to ignore .eslintrc and .eslintignore files (https://github.com/facebook/create-react-app/issues/2339)

I'm getting the `Useless constructor  @typescript-eslint/no-useless-constructor` warning from a ts file generated by autorest. The recommendation from the create-react-app team (along with closing the issue and locking against further discussion), is to either place `/* eslint-disable */` at the top of the file, or single line ignore comments on relevant lines, but I haven't been able to figure out how to make this happen automatically with autorest. 

I tried [mis]using `--license-header=eslint-disable`, which placed this comment at the top of each file:

```
/*
 * eslint-disable
 */
```

but apparently this format does not get picked up by eslint either, so I still get the error. Is there another way of prepending a generic header that I've missed, or some other means of commenting or templating? Or is there a way to cause autorest to not generate empty constructors? 

(note: I'm happy to work on a PR, but wanted to ask if there was either a current workaround and also to discuss what would be the preferable change) 

Version info: 
```
AutoRest code generation utility [cli version: 3.0.6187; node: v12.18.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      '/Users/toma/.autorest/@microsoft.azure_autorest-core@2.0.4417/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4417)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~4.2.0->4.2.4)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51->2.3.51)
```

Other possibly relevant versions:
- `"react-scripts": "3.4.1"`
- `"@azure/ms-rest-js": "2.0.7"`

**Comment by btmorr** [comment]
Ok, a little more information:

If I set the `EXTEND_ESLINT` environment variable when calling `react-scripts start`, and also completely remove the header from the file that is causing the warning, I do not get the warning. I cannot figure out why this is the case, but it compiles without warnings if either there is no header at all, or if the header is exactly:

```
/* eslint-disable */
```

The default header did not work, nor did any of the following:

```
/*
 * MIT
 */
```

```
/*
 * eslint-disable
 */
```

```
/*  */
```

Is there a way to tell the generator to put no header in the files whatsoever?

**Comment by btmorr** [comment]
I've been working on trying to understand how autorest core works, and have gotten as far as figuring out that this is where the magic strings for license headers are selected: https://github.com/Azure/autorest/blob/master/core/lib/configuration.ts#L539

This includes "NONE" as a possible option, which is very close to what I want, but it generates:

```
/*
 */
```

Which still generates the warning. I would like to propose that somehow in the case of "NONE" specifically, that no header at all would be added (with null/undefined still generating the default header as it does now). I'm happy to put up a PR to do this, or to set up my own fork if this or some other solution is not desirable, but I would really appreciate some help understanding where `ConfigurationView.GetEntry('license-header')` is called. It doesn't appear to be called explicitly anywhere, so it seems like it must be in the process of mapping over an array somewhere in the pipeline, but I haven't figured that part out. (also, it seems like the relevant parts may be implemented in Azure/autorest, rather than here, so I may have to either ask or make a PR there--please let me know if that's the case and the folks on this project aren't able to help, but I figure you all know how this works under the hood better than I do)

Any help would be incredibly appreciated!

**Comment by joheredi** [comment]
Hi @btmorr, thanks for your investigation! I agree that we shouldn't be generating an empty license header when NONE is passed.

It looks like the license header is set [here](https://github.com/Azure/autorest.typescript/blob/3f96f3f8e392da9193d4d468bb86663f34df3ad8/src/Program.cs#L120) and then used in several places when generating the files

CodeModelTSa.cs ([here ](https://github.com/Azure/autorest.typescript/blob/3f96f3f8e392da9193d4d468bb86663f34df3ad8/src/azure/Model/CodeModelTSa.cs#L119)and [here](https://github.com/Azure/autorest.typescript/blob/3f96f3f8e392da9193d4d468bb86663f34df3ad8/src/azure/Model/CodeModelTSa.cs#L163))

CodeModelTS.cs ([here](https://github.com/Azure/autorest.typescript/blob/3f96f3f8e392da9193d4d468bb86663f34df3ad8/src/vanilla/Model/CodeModelTS.cs#L814), [here](https://github.com/Azure/autorest.typescript/blob/3f96f3f8e392da9193d4d468bb86663f34df3ad8/src/vanilla/Model/CodeModelTS.cs#L1166) and [here](https://github.com/Azure/autorest.typescript/blob/3f96f3f8e392da9193d4d468bb86663f34df3ad8/src/vanilla/Model/CodeModelTS.cs#L814))

MethodGroupTS.cs ([here](https://github.com/Azure/autorest.typescript/blob/3f96f3f8e392da9193d4d468bb86663f34df3ad8/src/vanilla/Model/MethodGroupTS.cs#L205))

I think we could conditionally call `builder.Comment` when the header is not null or empty.

If you want to send a PR with the fix, it would be greatly appreciated 😄 ! When working on it, please create your branch off `v4x` instead of master and send the PR against `v4x`.

Also, I'm interested to see the "useless" constructor that is getting generated, any chance you could share your swagger?

**Comment by btmorr** [comment]
Thanks! I'll fork off of `v4x` and work on a PR. My swagger spec is here: https://github.com/btmorr/leifdb/blob/use-autorest/docs/swagger.json

That version is on a feature branch, and has a small modification off of the base branch. The one on the feature branch is the one I expect to go with once that branch is merged. The base branch link is here: https://github.com/btmorr/leifdb/blob/edge/docs/swagger.json

**Comment by btmorr** [comment]
It's a really simple application (K-V store with the most basic CRUD operations) from the user standpoint. The more complex messaging for distributed consensus is done using protobuf, so the public API ends up only having very simple endpoints.

**Comment by btmorr** [comment]
This is the file that is generating the warning: https://github.com/btmorr/leifdb/blob/use-autorest/ui/src/leifDbClientAPI.ts

**Comment by btmorr** [comment]
I put up a draft PR, and have some questions on there about how to invoke my development version of the typescript plugin, and how (if needed) to modify the test suite. Thanks in advance for the help (I've not written C# before, so I'm unfamiliar with a lot of the tooling).

**Comment by btmorr** [comment]
I also added a couple of statements to the readme, but I'm happy to reword or remove if they're not helpful or accurate.

**Comment by btmorr** [comment]
(added comments to the PR, figured out answers to most of my questions)

**Comment by joheredi** [comment]
@btmorr your PR has been merged thanks for your contribution! 
Closing this issue
