### ISSUE TITLE
[v6] Rename options.endpoint to options.baseUrl in generated ClientContext

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#702]
For consistency.

Investigate if this is still required. Are there any scenarios that can't be accomplished by parametrized host?

**Comment by daviwil** [comment]
@zolvarga ran into this issue when he started generating Digital Twins SDK after using `options.baseUrl` to set the service endpoint:

https://github.com/zolvarga/azure-sdk-for-js/commit/7e5e80f17ffb1be39319ed36fcc4fe2546f421d8#diff-671eed20263af916a3fbe4c71b3bde33L43

Technically this can/will be a breaking change for those upgrading to the v6 generator.

**Comment by ramya-rao-a** [comment]
@sarangan12 Please discuss this with the feature crew as well. What are the names being used by our friends in other languages?

**Comment by sarangan12** [comment]
@joheredi Let me get some clarification on this issue. Please let me know if my understanding is correct.Let me start with an example.

1. In the `SearchServiceClientContext` class file, we have the constructor as:
```js
export class SearchServiceClientContext extends coreClient.ServiceClient {
    constructor(endpoint: string, apiVersion: ApiVersion20210430Preview, options?: SearchServiceClientOptionalParams) {}
}
```

2. In the above code, if you look at the `SearchServiceClientOptionalParams` object, it looks like:
```js
export interface SearchServiceClientOptionalParams extends coreClient.ServiceClientOptions {
  endpoint?: string;
}
```

3. Now, the SDK user can set this endpoint while calling the client class. This endpoint will be set to `baseUri` which is defined in the `ServiceClientOptions` object in `core-client` package. 
```js
export declare interface ServiceClientOptions extends CommonClientOptions {
     baseUri?: string;
     .........
     .........
}
```

4. Now, I am assuming this issue is created to rename the `endPoint` in `options` to `baseUrl` (@joheredi why not `baseUri`???) to keep it consistent. 

Now, I have discussed with other SDK owners. All of them uses the name `endPoint`. Actually, Python has changed their name from `baseUri` to `endPoint`. 

To be consistent, I would recommend changing the `baseUri` to `endPoint` in `core-client` package. Any thoughts????

**Comment by joheredi** [comment]
I think we want to avoid the `URI` suffix as it is semantically (slightly) different to `URL`. 

Today, we generate `options.endpoint`, and in the the generated client we take that value (if present) and assign it to core-client's ServiceClientOptions `baseUri`.

```typescript
const optionsWithDefaults = {
      ...defaults,
      ...options,
      userAgentOptions: {
        userAgentPrefix
      },
      baseUri: options.endpoint || "http://localhost:3000"
    };
    super(optionsWithDefaults);
```

The problem with this is that while we create an alias for core-client's `baseUri` we are still exposing `baseUri` in the generated client options, but really just ignoring it. A customer would be able to call a generated client like this:

```typescript
new FooClient({baseUri: "ignored", endpoint: "preserved"})
```

I think your proposal is reasonable, it'll get rid of the `uri` suffix and be consistent with other languages. @bterlson, what do you think about `baseUri` becoming `endpoint` in core-client's `ServiceClientOptions`?

**Comment by bterlson** [comment]
+1 to `endpoint` from me.

**Comment by ramya-rao-a** [comment]
> To be consistent, I would recommend changing the baseUri to endPoint in core-client package

Am guessing to avoid making a major version update to core-client, we will be marking `baseUri` as deprecated and add `endPoint` to `ServiceClientOptions` and then update the code generator to set the endPoint instead of baseUri?

If so, then we don't need the breaking change label on this issue right?
