### ISSUE TITLE
Autorest typecript generator having issues ignoring type checking in node_modules 

### ISSUE THREAD

**Issue by andreskim** [Azure/autorest.typescript#883]
**Describe the bug**
I'm in the process of utilizing autorest to generate a client for one of our REST microservices. Whille attempting to use autorest to generate a service client, (specifically for typescript)  I ran into the following issue. 

After generating using Autorest with typescript flag: 
```
  - npm run build fails  due to type checking in node_modules
  - In order to manually fix this, we have to add a "skipLibCheck": true to the tsconfig compiler options. 
```

The issue arises since our workflow depends on running a script to use autorest to generate a client on a given instance. The current workaround would involve a convoluted script that uses vim to edit the tsconfig after generation. 

**Potential Solutions**
```
1. Add the skipLibCheck in the tsconfig.json on default
2. Or, Allow users to pass in a config for the tsconfig

```

**Comment by sarangan12** [comment]
@andreskim Thanks for considering autorest for generating SDK for your service. We could not add `skipLibCheck: true` by default to all the generated libraries. But, I realize that there might be cases (such as yours) where you know you would want to pass such a check. I think I could add a flag to achieve this. I will work on that and update this issue soon. Thanks.

**Comment by sarangan12** [comment]
@andreskim After discussion with my team, I believe it is not required to add this flag in the generator. Because, each project might have unique requirements around tsconfig flags and it would be too cumbersome to add flags for each one in the generator. (You can find the discussion in this issue: https://github.com/Azure/autorest.typescript/pull/1022)

My suggestion would be to:

1. Generate your library using autorest.
2. Then, you could modify the tsconfig manually for the first time. 
3. For the followup cases, you could set  use `--generate-metadata=false` when you execute autorest command. This will generate only the src files and will not override your tsconfig files. 

Please let me know if this resolves your issue or if you have any more questions or issues.

**Comment by sarangan12** [comment]
No more action items pending on this issue. Closing this issue. Feel free to reopen if you encounter the same issue again
