### ISSUE TITLE
Not including response headers

### ISSUE THREAD

**Issue by ffMathy** [Azure/autorest.typescript#897]
When fetching a response using the generated client in the browser, I only get the headers `Content-Type` and `Content-Size` in the `_response.headers` property of my response.

This is despite the fact that Chrome clearly shows many other headers included.

**Comment by sarangan12** [comment]
@ffMathy I have just checked the response headers section and I am able to read other headers also. In fact we have test cases for these scenarios such as https://github.com/Azure/autorest.typescript/blob/main/test/integration/azureSpecialProperties.spec.ts#L51. 

Please check if this works for you. Else, Please let me know with the exact scenario/code that you have problem with.

**Comment by ffMathy** [comment]
But you probably also have the headers defined in the Swagger.json file right? I'm talking about headers that aren't defined there.

Also, this issue may only affect the old client. Never tried with the new v2 one.

**Comment by sarangan12** [comment]
@ffMathy when you say old client, do you mean the package `@microsoft.azure/autorest.typescript`? Even in this old client, the **raw** response does have the headers (irrespective of whether they are defined in swagger) But, the response object (as defined in the swagger) will not have the additional headers which is expected and by design. 

Do you see the same results? Or Do you not see the additional headers even in the **raw** response?

**Comment by ffMathy** [comment]
No, V2 of the HTTP Client or whatever it is called 🙂

**Comment by sarangan12** [comment]
@ffMathy So, you are using @autorest/typescript package. I can see the headers in that also. Do you have a sample code/scenario that you tried and not able to get the headers? 

Because, I just tried it and able to read the headers. Also, we have a test scenario covering that too. https://github.com/Azure/autorest.typescript/blob/28ebb6e2920a1adbc0a6b79b8a6a2383566f274b/test/integration/azureSpecialProperties.spec.ts#L45

**Comment by ffMathy** [comment]
I see I was using the `parsedHeaders` property instead. So sorry!
