### ISSUE TITLE
[Core v2] Add parameter to allow insecure connection to be on by default

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/autorest.typescript#901]
This is needed so that the test suite for core v2 can work with the http test server

**Comment by sarangan12** [comment]
@sarangan12 Confirm with Jeremy and Close this task.

**Comment by sarangan12** [comment]
For rest-pipeline, by default we refuse to call http links. In order to enable that, in each request we should pass the flag `allow-insecure-connection` as part of requestOptions. 

1. Introduce a new flag in V6 SDK Generator
2. If the flag is set to true, then set the allow-insecure-connection to true in the requestOptions.

**Comment by sarangan12** [comment]
Jeremy has completed this task in the CoreV2Migration Branch. https://github.com/sarangan12/autorest.typescript/commits/CoreV2MigrationBranch
