### ISSUE TITLE
All fields are optional

### ISSUE THREAD

**Issue by ffMathy** [Azure/autorest.typescript#994]
Even if I have a field that is required and not nullable according to Swagger, the emitted typescript is:

```
interface MyModel {
    myField?: string
}
```

The `?` shouldn't be there.

**Comment by sarangan12** [comment]
@ffMathy Thanks for raising this issue. I have looked into the specific issue and here is what I found. Let me give you an example. First let us take a look at the swagger [here](https://github.com/Azure/azure-rest-api-specs/blob/d95c18e2d5fc678a1453c454d746fdce22d30122/specification/search/data-plane/Azure.Search/preview/2020-06-30-Preview/searchindex.json#L1198#L834)

```json
......
......
"SearchResult": {
      "properties": {
        "@search.score": {
             "type": "number",
             "format": "double",
             "readOnly": true,
             "x-ms-client-name": "Score",
             "x-nullable": false,
             "description": "The relevance score of the document compared to other documents returned by the query."
        },
        "@search.rerankerScore": {
          "type": "number",
          "format": "double",
          "readOnly": true,
          "x-ms-client-name": "RerankerScore",
          "x-nullable": true,
          "description": "The relevance score computed by the semantic ranker for the top search results. Search results are sorted by the RerankerScore first and then by the Score. RerankerScore is only returned for queries of type 'semantic'."
        },
.....
.....
```

In the above swagger snippet, the `SearchResult` object has 2 properties: `@search.score` and `@search.rerankerScore`. Now, Let us take a look at the generated code [here](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/search/search-documents/src/generated/data/models/index.ts#L155)

```js
......
......
export interface SearchResult {
        readonly _score: number;
        readonly rerankerScore?: number;
........
........
```

As you can see from the code above, the `_score` does not have a `?`. But, the `rerankerScore` does not have a `?`. **Why?** That is because of the `x-nullable` extension. If the extesion is set to `false`, then we will make it to a required field. Else, it will be an optional field, which is also the default behavior. 

With the above explanation, in your swagger, if you would like to make `myField` as a required field, Please set `x-nullable` to `false` in your swagger.

Please let me know if you have more questions.

**Comment by sarangan12** [comment]
No more action items pending on this issue. Closing this issue. Feel free to reopen if you encounter the same issue again

**Comment by ffMathy** [comment]
Thank you! 🙏
